PERIPHERALS = pit pwm adc
DRIVERS = led pacer usb_serial adxl345 panic nrf24 ledtape
SRC = hat.c mmelody.c

# Use low level of optimisation to simplify debugging
OPT = -O1

BOARD = hat

include ../../boards/board.mk

