PERIPHERALS = pit pwm adc
DRIVERS = led pacer usb_serial panic nrf24 button ledtape
SRC = racer.c

# Use low level of optimisation to simplify debugging
OPT = -O1

BOARD = racer

include ../../boards/board.mk
